config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  get 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :delete

  root 'welcome#index'

  resources :groups
  match 'groups/:id/remove/:user_id', to: 'groups#remove_user', via: [:delete], as: 'group_remove'

  resources :users, only: [:show, :index]

  match 'requests/user', to: 'requests#request_user', via: [:post]
  match 'requests/group', to: 'requests#request_group', via: [:post]
  match 'requests', to: 'requests#update', via: [:put, :patch]
  match 'requests', to: 'requests#destroy', via: [:delete]

  resources :links, only: [:create, :destroy, :new]

end

app/models/group.rb
class Group < ActiveRecord::Base
	include PgSearch

	pg_search_scope :search, :against => :name,
	associated_against: {user: :name},
	:using => {
			tsearch: {:dictionary => "english"}
		}

	geocoded_by :address
	after_validation :geocode, :if => :address_changed?

	has_many :users
	belongs_to :user, foreign_key: :user_id

	has_many :requests

	validates :address, :name, presence: true
	validates_uniqueness_of :name
	validates_uniqueness_of :user_id

	before_create :add_user

	def new_request(user)
		self.requests.new(user_id: user.id, group_confirm: true)
	end

	def unconfirmed_requests
		self.requests.where(group_confirm: false)
	end

	private
		def add_user
			self.users << self.user
		end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!
	before_action :user_has_group?, only: [:new, :create]
	before_action :authorize_user!, only: [:edit, :update, :destroy]
	before_action :load_group, only: [:show, :update, :edit, :destroy, :remove_user]

	def index
		respond_to do |format|
			format.json { render json: Group.search(params[:query]) }
			format.html do
				@groups = Group.all
				@hash = Gmaps4rails.build_markers(@groups) do |group, marker|
				  marker.lat group.latitude
				  marker.lng group.longitude
				  marker.infowindow  "<h6><a font-size='24px' href='/groups/#{group.id}'>#{group.name}</a><h6>"
				  # marker.picture({
				  # 	'url' => group.user.thumbnail,
				  # 	'width' => 36,
				  # 	'height' => 36
				  # })
				  marker.json({
				  	title: group.name
				  }) 
		end
			end
		end
	end

	def show
	end

	def new
		@group = current_user.build_group
	end

	def create
		@group = current_user.build_group(group_params)

		respond_to do |format|
			if @group.save
				format.html { redirect_to @group, notice: 'Group Created' }
			else
        format.html { render action: 'new' }
			end
		end
	end

	def edit
	end

	def update
		if @group.update_attributes(group_params)
			redirect_to group_path, :notice => "Group updated!"
		else
			render 'edit'
		end
	end

	def destroy
		if @group.destroy
			current_user.group_id = nil
			flash[:notice] = "Group destroyed!"
		else
			flash[:alert] = "Group was not destroyed!"
		end
		redirect_to groups_path
	end

	def remove_user
		@user = User.find(params[:user_id])
		if (current_user.owns?(@group) || @user == current_user) && @user != @group.user
			@group.users.delete(@user)
			@user.group = nil
			@user.requests.where(group_id: @group.id).first.destroy
			redirect_to group_path(@group.id), notice: "#{@user.name} has been removed from #{@group.name}"
		else
			redirect_to group_path(@group.id), alert: "You are not authorized to do this"
		end
	end

	private
		def load_group
			@group = Group.find(params[:id])
		end

		def group_params
			params.require(:group).permit(:name, :address)
		end

		def user_has_group?
			if current_user.group
				redirect_to '/'
				flash[:alert] = "You already have a group"
			end
		end

		def authorize_user!
			unless current_user.owns?(Group.find(params[:id]))
				redirect_to '/'
				flash[:alert] = "You are not authorized to do this"
			end
		end
end

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
	<%= f.input :name %>
	<%= f.input :address %>
	<%= f.button :submit %>
<% end %>

app/views/groups/_links.html.erb
<div class="button-bar">
  <ul class="button-group round">
  	<%= link_to "edit", edit_group_path(@group.id), class: 'tiny button' %>
		<%= link_to "destroy", group_path(@group.id), method: :delete, class: 'button tiny alert' %>
  </ul>
</div>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>

<%= render 'form' %>

app/views/groups/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<h2>Groups</h2>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">

	handler = Gmaps.build('Google');
	handler.buildMap({ 
			provider: {
				disableDefaultUI: true
			},
			internal: {
				id: 'map'
			}
		},function(){
		  markers = handler.addMarkers(<%= raw @hash.to_json %>);
		  handler.bounds.extendWith(markers);
		  handler.fitMapToBounds();
	});
	//buildMap(<%= raw @hash.to_json %>);
</script>

app/views/groups/new.html.erb
<h1>new group</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<h3>owner: <%= @group.user.name %></h3>

<div class="row">
  <div class="large-6 columns">
  	<table>
			<% @group.users.each do |user| %>
				<tr>
					<td><%= user.name %></td>
					<% if current_user.owns?(@group) %>
						<td><%= button_to('remove user', group_remove_path(id: @group.id, user_id: user.id), class: 'button tiny alert', method: :delete) unless user.owns?(@group) %></td>
					<% end %>
				</tr>
			<% end %>
		</table>
		<% if current_user.owns?(@group) %>
			<%= render 'links'  %>
		<% else %>
			<%= button_to('leave group', group_remove_path(id: @group.id, user_id: current_user.id), class: 'button tiny alert', method: :delete) if current_user.group == @group %>
		<% end %>
	</div>
  <div class="large-6 columns">
  	<% if current_user.owns?(@group) && @group.unconfirmed_requests.any? %>
			<table>
				<tr>
					<td>name</td>
				</tr>
				<% @group.unconfirmed_requests.each do |request| %>
					<td><%= link_to request.user.name, user_path(request.user.id) %></td>
				<% end %>
			</table>
  	<% end %>
  </div>
</div>

<% if can_request_group?(current_user, @group) %>
	<div id="request-form">
		<%= form_tag(requests_group_path, method: :post, remote: true) do %>
			<%= hidden_field_tag(:group_id, @group.id) %>
			<%= submit_tag('request to join!', class: 'button tiny') %>
		<% end %>
	</div>
<% end %>

<% if requested_user_by_group(current_user, @group) %>
	<%= form_tag(requests_path, method: :patch) do %>
		<%= hidden_field_tag(:user_id, current_user.id) %>
		<%= hidden_field_tag(:group_id, @group.id) %>
		<%= hidden_field_tag('request[user_confirm]', true) %>
		<%= submit_tag('accept user', class: 'button tiny') %>
	<% end %>
<% end %>

<% if requested_group_by_user(current_user, @group) %>
	<%= render 'requests/delete_form', user: current_user, group: @group %>
<% end %>