config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  get 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :delete

  root 'welcome#index'

  resources :groups
  match 'groups/:id/remove/:user_id', to: 'groups#remove_user', via: [:delete], as: 'group_remove'

  resources :users, only: [:show, :index]

  match 'requests/user', to: 'requests#request_user', via: [:post]
  match 'requests/group', to: 'requests#request_group', via: [:post]
  match 'requests', to: 'requests#update', via: [:put, :patch]
  match 'requests', to: 'requests#destroy', via: [:delete]

  resources :links, only: [:create, :destroy, :new]

end

app/models/user.rb
class User < ActiveRecord::Base
	include PgSearch

	has_many :links
	has_one :group, foreign_key: :user_id
	has_many :requests

	# validates :email, :name, :thumbnail, presence: true

	pg_search_scope :search, :against => :name,
		associated_against: {group: :name},
		:using => {
				tsearch: {:dictionary => "english"}
			}

	alias_method :old_group, :group
	def group
		return self.old_group if self.old_group
		Group.find(self.group_id) if self.group_id
	end

	def new_request(group)
		self.requests.new(group_id: group.id, user_confirm: true)
	end

	def can_request?
		self.group == nil || !self.owns?(self.group)
	end

	def unconfirmed_requests
		self.requests.where(user_confirm: false)
	end

	def create_group(params = nil)
		return false if self.group
		super
	end

	def build_group(params = nil)
		return false if self.group
		super
	end

	def owns?(obj)
		obj.user == self
	end

	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.email = auth.info.email
	    user.thumbnail = auth.info.image
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save!
	  end
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	
  def index
  	@users = User.search(params[:query])
  	respond_to do |format|
  		format.json {render json: @users, only: [:name, :id]}
  		format.html
  	end
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h2>Users</h2>

<% if @users.to_a.any? %>	
	<table>
		<tr>
			<td>name</td>
		</tr>
		<% @users.each do |user| %>
			<tr>
				<td><%= link_to user.name, user_path(user.id) %></td>
			</tr>
		<% end %>
	</table>
<% end %> <!-- if -->

app/views/users/show.html.erb
<h2><%= @user.name %></h2>

<div class="row">
  <div class="large-6 columns">
	</div>
  <div class="large-6 columns">
  	<% if current_user == @user && @user.unconfirmed_requests.any? %>
			<table>
				<tr>
					<td>name</td>
				</tr>
				<% @user.unconfirmed_requests.each do |request| %>
					<td><%= link_to request.group.name, group_path(request.group.id) %></td>
				<% end %>
			</table>
  	<% end %>

  	<%= render('links/show', user: @user) %>
  </div>
</div>

<% if can_request_user?(@user, current_user.group) %>
	<div id="request-form">
		<%= form_tag(requests_user_path, method: :post, remote: true) do %>
			<%= hidden_field_tag(:user_id, @user.id) %>
			<%= submit_tag('request to join!', class: 'button tiny') %>
		<% end %>
	</div>
<% end %>

<% if requested_group_by_user(@user, current_user.group) %>
	<%= form_tag(requests_path, method: :patch) do %>
		<%= hidden_field_tag(:user_id, @user.id) %>
		<%= hidden_field_tag(:group_id, current_user.group.id) %>
		<%= hidden_field_tag('request[group_confirm]', true) %>
		<%= submit_tag('accept user', class: 'button tiny') %>
	<% end %>
<% end %>


<% if requested_user_by_group(@user, current_user.group) %>
	<%= render 'requests/delete_form', user: @user, group: current_user.group %>
<% end %>