config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  get 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :delete

  root 'welcome#index'

  resources :groups
  match 'groups/:id/remove/:user_id', to: 'groups#remove_user', via: [:delete], as: 'group_remove'

  resources :users, only: [:show, :index]

  match 'requests/user', to: 'requests#request_user', via: [:post]
  match 'requests/group', to: 'requests#request_group', via: [:post]
  match 'requests', to: 'requests#update', via: [:put, :patch]
  match 'requests', to: 'requests#destroy', via: [:delete]

  resources :links, only: [:create, :destroy, :new]

end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user

	validates :url, :name, presence: true
	validates :url, :format => URI::regexp(%w(http https))
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_filter :authenticate_user!
	before_filter :load_link, only: [:destroy]

	def create
		@link = current_user.links.new(link_params)
		if @link.save
			@links = current_user.links
		else
      render :error
		end
	end

	def new
		@link = current_user.links.new
	end

	def destroy
		if current_user.owns?(@link) && @link.destroy 
			@links = current_user.links
		else
			render :error
		end
	end

	private
		def link_params
			params.require(:link).permit(:name, :content, :url)
		end

		def load_link
			@link = Link.find(params[:id])
		end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<div id='link-form'>
	<%= simple_form_for link, remote: true do |f| %>
		<%= f.input :name %>
		<%= f.input :url %>
		<%= f.button :submit %>
	<% end %>
</div>

app/views/links/_link.html.erb
<li class='link_<%= link.id %>'>
	<b><a href="<%= link.url %>"><%= link.name %></a></b>
	<small>(<%= time_ago_in_words(link.created_at) %>)</small>
	<% if link.user == current_user %>
		<small><%= link_to "remove", link_path(link.id), method: :delete, remote: true %></small>
	<% end %>
</li>

app/views/links/_list.html.erb
<h4 id="links-count"><%= pluralize(links.count, 'link') if links.count > 0 %></h4>
<ul class='links'>
	<% (links || []).each do |link| %>
		<%= render link %>
	<% end %>
</ul>

app/views/links/_show.html.erb
<div id='links_<%= user.id %>'>
	<%= link_to("new link", new_link_path, id: 'new-link', class: 'button tiny', remote: true) if current_user == user %>
  <%= render 'links/list', links: user.links %>
</div>

app/views/links/create.js.erb
var html = "<%= j(render(@link)) %>";
var $elem = $(html).hide();

$('#link-form').fadeOut('slow', function() {
	$(this).replaceWith("<a href='/links/new' data-remote='true' id='new-link' class='button tiny'>new link</a>");
	$(this).fadeIn('slow');	
});

$('#links_<%= @link.user_id %> ul').prepend($elem);
$elem.fadeIn();

$('#links-count').replaceWith("<h4 id='links-count'><%= pluralize(@links.count, 'link') if @links.count > 0 %></h4>");

toastr.success("New comment added");

app/views/links/destroy.js.erb
$('.link_<%= @link.id %>').fadeOut('slow', function() {
	this.remove();
	$('#links-count').replaceWith("<h4 id='links-count'><%= pluralize(@links.count, 'link') if @links.count > 0 %></h4>");
});

app/views/links/error.js.erb
<% if @link.errors.any? %>
	toastr.error("<%= @link.errors.full_messages.join(', ') %>");
<% else %>
	toastr.error("You are un authorized to do this!");
<% end %>

app/views/links/new.js.erb
$('#new-link').replaceWith("<%= j(render 'form', link: @link) %>");