config/routes.rb
Rails.application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  get 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :delete

  root 'welcome#index'

  resources :groups
  match 'groups/:id/remove/:user_id', to: 'groups#remove_user', via: [:delete], as: 'group_remove'

  resources :users, only: [:show, :index]

  match 'requests/user', to: 'requests#request_user', via: [:post]
  match 'requests/group', to: 'requests#request_group', via: [:post]
  match 'requests', to: 'requests#update', via: [:put, :patch]
  match 'requests', to: 'requests#destroy', via: [:delete]

  resources :links, only: [:create, :destroy, :new]

end

app/views/layouts/_search_form.html.erb
<form id="search-form">
	<div class="row collapse">
	  <div class="large-3 small-3 columns">
	    <select id="select-search">
	      <option>users</option>
	      <option>groups</option>
	    </select>
	  </div>
	  <div class="large-7 small-7 columns">
	    <%= text_field_tag :query, params[:query], id: 'query-input' %>
	  </div>
		<div class="large-2 small-2 columns">
			<%= submit_tag "search", class: 'button tiny' %>
		</div>
	</div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "DevYoung" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">DevYoung</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li>
            <% if current_user %>
              <%= link_to "Sign out", signout_path, id: "sign_out", method: :delete %>
            <% else %>
              <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
            <% end %>
          </li>

          <% if current_user %>
            <li class="has-dropdown">
              <a href="#">groups</a>
              <ul class="dropdown">
                <li><%= link_to "all groups", groups_path %></li>
                <% if current_user.group %>
                  <li><%= link_to "my group", group_path(current_user.group.id) if current_user.group.id %></li>
                <% else %>
                  <li><%= link_to "create group", new_group_path %></li>
                <% end %> <!-- if -->
              </ul>
            </li>
          <% end %> <!-- if -->
        </ul>

        <!-- Left Nav Section -->
        <ul class="left">
          <% if current_user %>
            <li>
              <a href="/users/<%= current_user.id %>">
                <%= image_tag current_user.thumbnail, size: '25', class: 'th' %>
                <%= current_user.name %>
              </a>
            </li>
            <li class="has-form">
              <%= render 'layouts/search_form', path: users_path %>
            </li>
          <% end %> <!-- if -->
        </ul>
      </section>
    </nav>
      
    <div id="reveal">
      <div id="searchModel" class="reveal-modal" data-reveal>
        <h1>results</h1>
        <ul id='search-results'>

        </ul>
        <a class="close-reveal-modal">&#215;</a>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
    <%= flash_to_toastr %>

    <div class="row">
      <div class="panel">
        <%= yield %>
      </div>
    </div>
  </body>
</html>